---
driver:
  name: vagrant
  customize:
    memory: 2048
#  vm_hostname: kitchen

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: debian-7.2.0

suites:
  - name: mysql
    run_list: recipe[laravel]
    attributes:
      laravel:
        database_driver: mysql
        project_root: /srv
        project_name: test-app
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
  - name: pgsql
    run_list: recipe[laravel]
    attributes:
      laravel:
        database_driver: pgsql
        project_name: test-app
        project_root: /srv
      postgresql:
        version: 9.3
#        enable_pgdg_apt: false
        password:
          postgres: rootpass
        config:
          ssl: false
#          ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
#          ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
  - name: nginx-mysql
    run_list: recipe[laravel]
    attributes:
      laravel:
        webserver: nginx
        database_driver: mysql
        project_root: /srv
        project_name: test-app
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass

  - name: nginx-pgsql
    run_list: recipe[laravel]
    attributes:
      laravel:
        webserver: nginx
        database_driver: pgsql
        project_name: test-app
        project_root: /srv
      postgresql:
        version: 9.3
#        enable_pgdg_apt: true
        password:
          postgres: rootpass
        config:
          ssl: false
#          ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
#          ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
